[package]
name = "relay-wococo-client"
version = "0.1.0"
authors = ["AXIA Technologies <admin@axiacoin.network>"]
edition = "2018"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"

[dependencies]
codec = { package = "axia-scale-codec", version = "2.0.0" }
headers-relay = { path = "../headers" }
relay-axlib-client = { path = "../client-axlib" }
relay-utils = { path = "../utils" }

# Bridge dependencies
bridge-runtime-common = { path = "../../bin/runtime-common" }
bp-header-chain = { path = "../../primitives/header-chain" }
bp-message-dispatch = { path = "../../primitives/message-dispatch" }
bp-messages = { path = "../../primitives/messages" }
bp-axia-core = { path = "../../primitives/axia-core" }
bp-betanet = { path = "../../primitives/chain-betanet" }
bp-runtime = { path = "../../primitives/runtime" }
bp-wococo = { path = "../../primitives/chain-wococo" }
pallet-bridge-dispatch = { path = "../../modules/dispatch" }
pallet-bridge-messages = { path = "../../modules/messages" }

# Axlib Dependencies
frame-system = { git = "https://github.com/axia-tech/axia-core", branch = "dev" }
frame-support = { git = "https://github.com/axia-tech/axia-core", branch = "dev" }
pallet-transaction-payment = { git = "https://github.com/axia-tech/axia-core", branch = "dev" }
sp-core = { git = "https://github.com/axia-tech/axia-core", branch = "dev" }
sp-keyring = { git = "https://github.com/axia-tech/axia-core", branch = "dev" }
sp-runtime = { git = "https://github.com/axia-tech/axia-core", branch = "dev" }
