[package]
name = "test-allychain-adder"
version = "0.9.12"
authors = ["AXIA Technologies <admin@axiacoin.network>"]
description = "Test allychain which adds to a number as its state transition"
edition = "2018"
build = "build.rs"

[dependencies]
allychain = { package = "axia-allychain", path = "../../", default-features = false, features = [ "wasm-api" ] }
axc-scale-codec = { version = "2.3.1", default-features = false, features = ["derive"] }
sp-std = { git = "https://github.com/axia-tech/axia-core", default-features = false , branch = "dev" }
tiny-keccak = { version = "2.0.2", features = ["keccak"] }
dlmalloc = { version = "0.2.1", features = [ "global" ] }

# We need to make sure the global allocator is disabled until we have support of full axlib externalities
sp-io = { git = "https://github.com/axia-tech/axia-core", default-features = false, features = [ "disable_allocator" ] , branch = "dev" }

[build-dependencies]
axlib-wasm-builder = { git = "https://github.com/axia-tech/axia-core", branch = "dev" }

[features]
default = [ "std" ]
std = [
	"allychain/std",
	"sp-std/std",
]
