[package]
name = "test-allychain-adder"
version = "0.9.17"
authors = ["Axia Technologies <admin@axia.io>"]
description = "Test allychain which adds to a number as its state transition"
edition = "2018"
build = "build.rs"

[dependencies]
allychain = { package = "axia-allychain", path = "../../", default-features = false, features = [ "wasm-api" ] }
axia-scale-codec = { version = "2.3.1", default-features = false, features = ["derive"] }
sp-std = { git = "https://github.com/axia-tech/axlib", default-features = false , branch = "axlib" }
tiny-keccak = { version = "2.0.2", features = ["keccak"] }
dlmalloc = { version = "0.2.3", features = [ "global" ] }

# We need to make sure the global allocator is disabled until we have support of full axlib externalities
sp-io = { git = "https://github.com/axia-tech/axlib", default-features = false, features = [ "disable_allocator" ] , branch = "axlib" }

[build-dependencies]
axlib-wasm-builder = { git = "https://github.com/axia-tech/axlib", branch = "axlib" }

[features]
default = [ "std" ]
std = [
	"allychain/std",
	"sp-std/std",
]
