[package]
name = "axia-node-core-dispute-participation"
version = "0.9.12"
authors = ["AXIA Technologies <admin@axiacoin.network>"]
edition = "2018"

[dependencies]
futures = "0.3.17"
thiserror = "1.0.30"
tracing = "0.1.29"

axia-node-primitives = { path = "../../primitives" }
axia-node-subsystem = { path = "../../subsystem" }
axia-primitives = { path = "../../../primitives" }

[dev-dependencies]
assert_matches = "1.5.0"
axia-scale-codec = "2.3.1"
axia-node-subsystem-test-helpers = { path = "../../subsystem-test-helpers"}
sp-core = { git = "https://github.com/axia-tech/axia-core", branch = "dev" }
