[package]
name = "xcm-simulator-fuzzer"
version = "0.9.9"
authors = ["AXIA Technologies <admin@axiacoin.network>"]
description = "Examples of xcm-simulator usage."
edition = "2018"

[dependencies]
codec = { package = "axia-scale-codec", version = "2.0.0" }
honggfuzz = "0.5.54"
scale-info = { version = "1.0", features = ["derive"] }

frame-system = { git = "https://github.com/axia-tech/axia-core", branch = "dev" }
frame-support = { git = "https://github.com/axia-tech/axia-core", branch = "dev" }
pallet-balances = { git = "https://github.com/axia-tech/axia-core", branch = "dev" }
sp-std = { git = "https://github.com/axia-tech/axia-core", branch = "dev" }
sp-core = { git = "https://github.com/axia-tech/axia-core", branch = "dev" }
sp-runtime = { git = "https://github.com/axia-tech/axia-core", branch = "dev" }
sp-io = { git = "https://github.com/axia-tech/axia-core", branch = "dev" }

xcm = { path = "../../" }
xcm-simulator = { path = "../" }
xcm-executor = { path = "../../xcm-executor" }
xcm-builder = { path = "../../xcm-builder" }
pallet-xcm = { path = "../../pallet-xcm" }
axia-core-primitives = { path = "../../../core-primitives" }
axia-runtime-allychains = { path = "../../../runtime/allychains" }
axia-allychain = { path = "../../../allychain" }

[[bin]]
path = "src/fuzz.rs"
name = "xcm-fuzzer"
