{
 "title": "Ethereum PoA to Rialto Exchange Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Best finalized blocks",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "Ethereum_to_Axlib_Exchange_best_block_numbers",
     "legendFormat": "Best {{type}} block"
    }
   ]
  },
  {
   "title": "Number of processed blocks since last restart",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "Ethereum_to_Axlib_Exchange_processed_blocks"
    }
   ]
  },
  {
   "title": "Average System Load",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "Ethereum_to_Axlib_Exchange_system_average_load",
     "legendFormat": "Average system load in last {{over}}"
    }
   ]
  },
  {
   "title": "Relay Process CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "Ethereum_to_Axlib_Exchange_process_cpu_usage_percentage",
     "legendFormat": "1 CPU = 100"
    }
   ]
  },
  {
   "title": "Number of processed transactions since last restart",
   "type": "stat",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "Ethereum_to_Axlib_Exchange_processed_transactions",
     "legendFormat": "{{type}} transactions"
    }
   ]
  },
  {
   "title": "Memory Usage for Relay Process",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "Ethereum_to_Axlib_Exchange_process_memory_usage_bytes / 1024 / 1024",
     "legendFormat": "Process memory, MB"
    }
   ]
  }
 ]
}