[package]
name = "relay-rialto-client"
version = "0.1.0"
authors = ["Axia Technologies <admin@axia.io>"]
edition = "2018"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"

[dependencies]
codec = { package = "axia-scale-codec", version = "2.2.0" }
relay-axlib-client = { path = "../client-axlib" }
relay-utils = { path = "../utils" }

# Bridge dependencies

bp-rialto = { path = "../../primitives/chain-rialto" }
rialto-runtime = { path = "../../bin/rialto/runtime" }

# Axlib Dependencies

frame-system = { git = "https://github.com/axia-tech/axlib", branch = "axlib" }
frame-support = { git = "https://github.com/axia-tech/axlib", branch = "axlib" }
pallet-transaction-payment = { git = "https://github.com/axia-tech/axlib", branch = "axlib" }
sp-core = { git = "https://github.com/axia-tech/axlib", branch = "axlib" }
sp-runtime = { git = "https://github.com/axia-tech/axlib", branch = "axlib" }
