[package]
name = "type-utils"
authors = ['Axia Network <https://github.com/Axia-Tech>']
edition = '2018'
license = 'GPL-3.0'
homepage = 'https://axia.finance'
repository = 'https://github.com/AxiaCoin/Axia-Network-axia/tree/master'
version = '0.9.0'

[dependencies]
