[package]
name = "axia-node-core-candidate-validation"
version = "0.9.12"
authors = ["AXIA Technologies <admin@axiacoin.network>"]
edition = "2018"

[dependencies]
async-trait = "0.1.51"
futures = "0.3.17"
tracing = "0.1.29"

sp-maybe-compressed-blob = { package = "sp-maybe-compressed-blob", git = "https://github.com/axia-tech/axia-core", branch = "dev" }
axc-scale-codec = { version = "2.3.1", default-features = false, features = ["bit-vec", "derive"] }

axia-primitives = { path = "../../../primitives" }
axia-allychain = { path = "../../../allychain" }
axia-node-primitives = { path = "../../primitives" }
axia-node-subsystem = { package = "axia-node-subsystem", path = "../../subsystem" }
axia-node-subsystem-util = { path = "../../subsystem-util" }

[target.'cfg(not(any(target_os = "android", target_os = "unknown")))'.dependencies]
axia-node-core-pvf = { path = "../pvf" }

[dev-dependencies]
sp-keyring = { git = "https://github.com/axia-tech/axia-core", branch = "dev" }
futures = { version = "0.3.17", features = ["thread-pool"] }
assert_matches = "1.4.0"
axia-node-subsystem-test-helpers = { path = "../../subsystem-test-helpers" }
sp-core = { git = "https://github.com/axia-tech/axia-core", branch = "dev" }
