[package]
name = "storage-proof-fuzzer"
version = "0.1.0"
authors = ["AXIA Technologies <admin@axiacoin.network>"]
edition = "2018"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
codec = { package = "axc-scale-codec", version = "2.0.0" }
finality-grandpa = "0.14.4"
hash-db = "0.15.2"
honggfuzz = "0.5.54"
log = "0.4.0"
env_logger = "0.8.3"

# Bridge Dependencies

bp-header-chain = { path = "../../primitives/header-chain" }
bp-runtime = { path = "../../primitives/runtime" }
bp-test-utils = { path = "../../primitives/test-utils" }

# Axlib Dependencies

frame-support = { git = "https://github.com/axia-tech/axia-core", branch = "dev" }
frame-system = { git = "https://github.com/axia-tech/axia-core", branch = "dev" }
sp-core = { git = "https://github.com/axia-tech/axia-core", branch = "dev" }
sp-finality-grandpa = { git = "https://github.com/axia-tech/axia-core", branch = "dev" }
sp-io = { git = "https://github.com/axia-tech/axia-core", branch = "dev" }
sp-runtime = { git = "https://github.com/axia-tech/axia-core", branch = "dev" }
sp-state-machine = { git = "https://github.com/axia-tech/axia-core", branch = "dev" }
sp-std = { git = "https://github.com/axia-tech/axia-core", branch = "dev" }
sp-trie = { git = "https://github.com/axia-tech/axia-core", branch = "dev" }
