[package]
name = "axia-dispute-distribution"
version = "0.9.12"
authors = ["AXIA Technologies <admin@axiacoin.network>"]
edition = "2018"

[dependencies]
futures = "0.3.17"
tracing = "0.1.29"
derive_more = "0.99.14"
axia-scale-codec = { version = "2.3.1", features = ["std"] }
axia-primitives = { path = "../../../primitives" }
axia-erasure-coding = { path = "../../../erasure-coding" }
axia-subsystem = { package = "axia-node-subsystem", path = "../../subsystem" }
axia-node-network-protocol = { path = "../../network/protocol" }
axia-node-subsystem-util = { path = "../../subsystem-util" }
axia-node-primitives = { path = "../../primitives" }
sc-network = { git = "https://github.com/axia-tech/axia-core", branch = "dev" }
sp-application-crypto = { git = "https://github.com/axia-tech/axia-core", branch = "dev" }
sp-keystore = { git = "https://github.com/axia-tech/axia-core", branch = "dev" }
thiserror = "1.0.30"
lru = "0.7.0"

[dev-dependencies]
async-trait = "0.1.51"
axia-subsystem-testhelpers = { package = "axia-node-subsystem-test-helpers", path = "../../subsystem-test-helpers" }
sp-keyring = { git = "https://github.com/axia-tech/axia-core", branch = "dev" }
sp-tracing = { git = "https://github.com/axia-tech/axia-core", branch = "dev" }
sc-keystore = { git = "https://github.com/axia-tech/axia-core", branch = "dev" }
futures-timer = "3.0.2"
assert_matches = "1.4.0"
lazy_static = "1.4.0"
