[package]
name = "axia-node-core-allychains-inherent"
version = "0.9.12"
authors = ["AXIA Technologies <admin@axiacoin.network>"]
edition = "2018"

[dependencies]
futures = "0.3.17"
futures-timer = "3.0.2"
tracing = "0.1.29"
thiserror = "1.0.30"
async-trait = "0.1.51"
axia-node-subsystem = { path = "../../subsystem" }
axia-primitives = { path = "../../../primitives" }
sp-blockchain = { git = "https://github.com/axia-tech/axia-core", branch = "dev" }
sp-inherents = { git = "https://github.com/axia-tech/axia-core", branch = "dev" }
sp-runtime = { git = "https://github.com/axia-tech/axia-core", branch = "dev" }
