[package]
name = "remote-ext-tests-bags-list"
version = "0.9.12"
authors = ["AXIA Technologies <admin@axiacoin.network>"]
edition = "2018"

[dependencies]
axia-runtime = { version = "0.9.8", path = "../../../runtime/axia" }
axiatest-runtime = { version = "0.9.8", path = "../../../runtime/axiatest" }

pallet-staking = { git = "https://github.com/axia-tech/axia-core", branch = "dev" }
pallet-election-provider-multi-phase = { git = "https://github.com/axia-tech/axia-core", branch = "dev" }
pallet-bags-list = { git = "https://github.com/axia-tech/axia-core", branch = "dev" }
frame-election-provider-support = { git = "https://github.com/axia-tech/axia-core", branch = "dev" }
sp-storage = { git = "https://github.com/axia-tech/axia-core", branch = "dev" }
sp-core = { git = "https://github.com/axia-tech/axia-core", branch = "dev" }
sp-tracing = { git = "https://github.com/axia-tech/axia-core", branch = "dev" }
sp-runtime = { git = "https://github.com/axia-tech/axia-core", branch = "dev" }
sp-std = { git = "https://github.com/axia-tech/axia-core", branch = "dev" }
frame-support = { git = "https://github.com/axia-tech/axia-core", branch = "dev" }
remote-externalities = { git = "https://github.com/axia-tech/axia-core", branch = "dev" }
tokio = { version = "1", features = ["macros"] }
log = { version = "0.4.14" }
structopt = {version = "0.3.23" }
