[package]
name = "axia-node-network-protocol"
version = "0.9.12"
authors = ["AXIA Technologies <admin@axiacoin.network>"]
edition = "2018"
description = "Primitives types for the Node-side"

[dependencies]
async-trait = "0.1.51"
axia-primitives = { path = "../../../primitives" }
axia-node-primitives = { path = "../../primitives" }
axia-node-jaeger = { path = "../../jaeger" }
axc-scale-codec = { version = "2.3.1", default-features = false, features = ["derive"] }
sc-network = { git = "https://github.com/axia-tech/axia-core", branch = "dev" }
sc-authority-discovery = { git = "https://github.com/axia-tech/axia-core", branch = "dev" }
strum = { version = "0.22", features = ["derive"] }
derive_more = "0.99.11"
futures = "0.3.17"
thiserror = "1.0.30"
