[package]
name = "axia-node-core-dispute-coordinator"
version = "0.9.12"
authors = ["AXIA Technologies <admin@axiacoin.network>"]
edition = "2018"

[dependencies]
bitvec = { version = "0.20.1", default-features = false, features = ["alloc"] }
futures = "0.3.17"
tracing = "0.1.29"
axc-scale-codec = "2"
kvdb = "0.10.0"
derive_more = "0.99.14"
thiserror = "1.0.30"

axia-primitives = { path = "../../../primitives" }
axia-node-primitives = { path = "../../primitives" }
axia-node-subsystem = { path = "../../subsystem" }
axia-node-subsystem-util = { path = "../../subsystem-util" }

sc-keystore = { git = "https://github.com/axia-tech/axia-core", branch = "dev" }

[dev-dependencies]
kvdb-memorydb = "0.10.0"
axia-node-subsystem-test-helpers = { path = "../../subsystem-test-helpers" }
sp-keyring = { git = "https://github.com/axia-tech/axia-core", branch = "dev" }
sp-core = { git = "https://github.com/axia-tech/axia-core", branch = "dev" }
sp-keystore = { git = "https://github.com/axia-tech/axia-core", branch = "dev" }
assert_matches = "1.4.0"

[features]
# If not enabled, the dispute coordinator will do nothing.
disputes = []
