[package]
name = "bp-test-utils"
version = "0.1.0"
authors = ["AXIA Technologies <admin@axiacoin.network>"]
edition = "2018"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"

[dependencies]
bp-header-chain = { path = "../header-chain", default-features = false  }
codec = { package = "axia-scale-codec", version = "2.0.0", default-features = false }
ed25519-dalek = { version = "1.0", default-features = false, features = ["u64_backend"] }
finality-grandpa = { version = "0.14.4", default-features = false }
sp-application-crypto = { git = "https://github.com/axia-tech/axia-core", default-features = false , branch = "dev" }
sp-finality-grandpa = { git = "https://github.com/axia-tech/axia-core", default-features = false  , branch = "dev" }
sp-runtime = { git = "https://github.com/axia-tech/axia-core", default-features = false , branch = "dev" }
sp-std = { git = "https://github.com/axia-tech/axia-core", default-features = false , branch = "dev" }

[features]
default = ["std"]
std = [
	"bp-header-chain/std",
	"codec/std",
	"ed25519-dalek/std",
	"finality-grandpa/std",
	"sp-application-crypto/std",
	"sp-finality-grandpa/std",
	"sp-runtime/std",
	"sp-std/std",
]
